source = ~/.config/hypr/hyprlock/colors.conf

# Blurred Dynamic Wallpaper Backdrop
background {
    monitor =
    path = $background_image
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.75
    vibrancy = 0.1696
    vibrancy_darkness = 0.05
}

# Big Digital Clock
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = $text_color
    font_size = 90
    font_family = $font_family_clock
    position = 0, 240
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
}

# Date Label
label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d"
    color = $text_color
    font_size = 20
    font_family = $font_family
    position = 0, 160
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
}

# User Profile Avatar Image
image {
    monitor =
    path = /home/raven/.config/hypr/profile.jpg
    size = 110
    rounding = -1 # Circular
    border_size = 3
    border_color = $entry_border_color
    position = 0, 35
    halign = center
    valign = center
    shadow_passes = 2
}

# Username Label
label {
    monitor =
    text = raven
    color = $text_color
    font_size = 16
    font_family = $font_family
    position = 0, -45
    halign = center
    valign = center
}

# Modern Password Input Field
input-field {
    monitor =
    size = 280, 48
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.25
    dots_center = true
    outer_color = $entry_border_color
    inner_color = $entry_background_color
    font_color = $entry_color
    fade_on_empty = false
    placeholder_text = <span foreground="##ffffff88"><i>Enter Password...</i></span>
    hide_input = false
    rounding = 24
    position = 0, -105
    halign = center
    valign = center
    shadow_passes = 2
}

# Keyboard Layout Indicator (e.g. US / MM)
label {
    monitor =
    text = cmd[update:1000] hyprctl devices | grep -A 3 at-translated-set-2-keyboard | grep 'active keymap' | sed 's/.*active keymap: //'
    color = $text_color
    font_size = 13
    font_family = $font_family
    position = -30, 30
    halign = right
    valign = bottom
}

# Battery Status / SysInfo
label {
    monitor =
    text = cmd[update:5000] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprlock/status.sh
    color = $text_color
    font_size = 13
    font_family = $font_family
    position = 30, 30
    halign = left
    valign = bottom
}
